### ISSUE TITLE
reload from dynamo every few minutes

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#1]
`DynamoHosts` should reload from Dynamo every few moments

<hr id='w'>

 - ~~`1-f2c33b38`/#90~~
 - `90-43f9c549`/#292 (by )

**Comment by davvd** [comment]
@yegor256 last puzzled solved `90-43f9c549`/#292

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#352](https://github.com/yegor256/s3auth/issues/352), [#90](https://github.com/yegor256/s3auth/issues/90).
