### ISSUE TITLE
HttpFacadeTest.java:515-518: For some reason this test...

### ISSUE THREAD

**Issue by davvd** [yegor256/s3auth#191]
Puzzle `8-5eb4ae33` in `s3auth-relay/src/test/java/com/s3auth/relay/HttpFacadeTest.java:515-518` has to be resolved: For some reason this test is not passing in Travis and Rultor, even with the jcabi-ssl-maven-plugin. It does work on my local machine. It fails with javax.net.ssl.SSLHandshakeException with message: Received fatal alert: handshake_failure. Let's investigate and fix.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by wentwog** [comment]
this task is waiting the fix of jcabi/jcabi-ssl-maven-plugin#17.

**Comment by davvd** [comment]
Closing..

**Comment by davvd** [comment]
oops, my bad, reopening

**Comment by wentwog** [comment]
@davvd the PL is merged, could you close the issue ?

**Comment by davvd** [comment]
the code made here contains a puzzle `191-7e266bd1`, which will be resolved soon

**Comment by davvd** [comment]
The task is closed, thanks everybody

**Comment by davvd** [comment]
@wentwog Thanks for your contribution, **30 mins** was added to your account, payment ID is `51586475`. +30 added to your rating, current score is: [+185](http://www.netbout.com/b/35104?open=rating)

**Comment by davvd** [comment]
@yegor256 last puzzled solved `191-7e266bd1`/#290

**Comment by 0pdd** [comment]
@davvd the puzzle [#397](https://github.com/yegor256/s3auth/issues/397) is still not solved.
