### ISSUE TITLE
NPE in withBody()

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#198]
probably related to #183

production logs

```
Jul 31 17:22:30 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 182µs
Jul 31 17:23:41 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 161µs
Jul 31 17:24:52 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 187µs
Jul 31 17:26:05 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 180µs
Jul 31 17:27:14 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 180µs
Jul 31 17:28:25 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 180µs
Jul 31 17:29:35 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 179µs
Jul 31 17:30:47 relay.s3auth.com user: [ERROR] c793b96 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 174µs

```

**Comment by davvd** [comment]
@dpisarenko you're working with this issue for 7 days already

-5 to your rating, your total score is [+165](http://www.netbout.com/b/35089?open=rating)

**Comment by davvd** [comment]
@dpisarenko don't work with it any more, someone else will continue. Thanks!

**Comment by davvd** [comment]
@alevohin this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by alevohin** [comment]
@yegor256 How do you start you production server? I need to know how classpath is provided for application.

**Comment by yegor256** [comment]
@alevohin we start it with Maven and this pom.xml: https://github.com/yegor256/s3auth/blob/master/s3auth-relay/src/main/production/pom.xml

**Comment by alevohin** [comment]
@yegor256 thanks. 
1) Could you give me startup log from production?
2) Does this NPE exist now in production logs?
3) Did this NPE exist before https://github.com/yegor256/s3auth/issues/183 ?

**Comment by yegor256** [comment]
@alevohin this is a portion of today log

```
Jan 05 10:01:17 relay.s3auth.com user: [ERROR] 4e7d1b7 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 175µs
Jan 05 10:03:05 relay.s3auth.com user: [ERROR] 4e7d1b7 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 178µs
Jan 05 11:00:29 relay.s3auth.com user: [ERROR] 4e7d1b7 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 192µs
Jan 05 11:00:35 relay.s3auth.com user: [ERROR] 4e7d1b7 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 179µs
Jan 05 11:02:20 relay.s3auth.com user: [ERROR] 4e7d1b7 com.s3auth.relay.HttpResponse: #withBody(NULL): thrown java.lang.NullPointerException out of com.s3auth.hosts.Resource$PlainText#<init>[125] in 143µs
```

There is nothing in logs on startup. It starts quietly, no errors/exceptions.

Yes, this bug is about a year old and it doesn't go away

**Comment by alevohin** [comment]
@yegor256 thanks!
Does log file contain full stacktrace of NPE?

**Comment by yegor256** [comment]
@alevohin nope :( maybe we can add some additional null-check to the method and throw a more verbose exception? usually, when such a problem exists, I think it's better to start improving the code around it by making it more verbose in case of an error. eventually, we'll hit the root cause of the original problem

**Comment by alevohin** [comment]
@yegor256 ok. I added stacktrace to log and some more logging at pull request https://github.com/yegor256/s3auth/pull/245.
I couldn't reproduce this problem locally, need more information from log.

**Comment by alevohin** [comment]
@yegor256 PR https://github.com/yegor256/s3auth/pull/245 merged. Let's deploy it and then look for errors with stacktrace.

**Comment by yegor256** [comment]
@rultor deploy pls

**Comment by yegor256** [comment]
@alevohin I think we're done in this task. Once I see the new logs, I'll create a new ticket. Thanks!

**Comment by davvd** [comment]
@alevohin Much obliged! I've added **30 mins** to your account in payment "50003414"; +30 added to your rating, current score is: [+135](http://www.netbout.com/b/35105?open=rating)
