### ISSUE TITLE
Migrate s3auth-rest integration tests to CasperJS

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/s3auth#200]
We're currently using the `rexsl-maven-plugin` package in order to perform integration testing on `s3auth-rest` pages. However, it's been made obsolete after version 1.0 of ReXSL.

Hence, it would be great if we can migrate to another form of automated testing, such as CasperJS. See http://www.yegor256.com/2014/06/21/casperjs-with-maven.html. I think it's better if we do it even before migrating to the latest ReXSL version (see #196).

**Comment by davvd** [comment]
@wentwog you're holding this ticket for 8 days already. If it's not finished (and closed) in the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -5 added to your rating, at the moment it is: +25

**Comment by wentwog** [comment]
@davvd  I understand. Sorry. Better give this task to someone else since I feel I won't be able to meet the deadline.

**Comment by davvd** [comment]
> @davvd  I understand. Sorry. Better give this task to someone else since I feel I won't be able to meet the deadline.

@wentwog got it, someone else will be assigned soon

**Comment by davvd** [comment]
@palyuga This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by palyuga** [comment]
@carlosmiranda PR is merged, I've left **todo** in code saying we need to migrate old rexsl tests. Can we close this issue?

**Comment by carlosmiranda** [comment]
@palyuga Sure, thanks!

**Comment by davvd** [comment]
there is a puzzle in this code `200-e1abb509`, we'll resolve it later

**Comment by davvd** [comment]
@palyuga Much obliged! I've added **30 mins** to your account in payment "50003424". +30 added to your rating, current score is: +45

**Comment by davvd** [comment]
@carlosmiranda the last puzzle `200-e1abb509`/#253 originated from here solved

**Comment by 0pdd** [comment]
@carlosmiranda the puzzle [#389](https://github.com/yegor256/s3auth/issues/389) is still not solved.

**Comment by 0pdd** [comment]
@carlosmiranda the only puzzle [#354](https://github.com/yegor256/s3auth/issues/354) is solved here.
