### ISSUE TITLE
Timeout waiting for connection from pool (again)

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#202]
```
Aug 19 14:09:08 relay.s3auth.com user: [ERROR] 271ac0c com.s3auth.hosts.DefaultResource: #headers(): thrown com.amazonaws.AmazonClientException(Unable to execute HTTP request: Timeout waiting for connection from pool) out of com.amazonaws.http.AmazonHttpClient#executeHelper[454] in 3min
Aug 19 14:09:08 relay.s3auth.com user: [ERROR] 271ac0c com.s3auth.relay.HttpResponse: #send(Socket[addr=/193.106.245.162,port=58688,localport=80]): thrown com.amazonaws.AmazonClientException(Unable to execute HTTP request: Timeout waiting for connection from pool) out of com.amazonaws.http.AmazonHttpClient#executeHelper[454] in 3min
Aug 19 14:12:30 relay.s3auth.com user: [ERROR] 271ac0c com.s3auth.hosts.DefaultResource: #headers(): thrown com.amazonaws.AmazonClientException(Unable to execute HTTP request: Timeout waiting for connection from pool) out of com.amazonaws.http.AmazonHttpClient#executeHelper[454] in 3min
Aug 19 14:12:30 relay.s3auth.com user: [ERROR] 271ac0c com.s3auth.relay.HttpResponse: #send(Socket[addr=/193.106.245.162,port=58691,localport=80]): thrown com.amazonaws.AmazonClientException(Unable to execute HTTP request: Timeout waiting for connection from pool) out of com.amazonaws.http.AmazonHttpClient#executeHelper[454] in 3min
```

**Comment by davvd** [comment]
@dpisarenko it's not your task any more, please stop working with it (if you were)

**Comment by davvd** [comment]
@marczeeee please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by Marczeeee** [comment]
@yegor256 The biggest problem with this issue is how to reproduce the situation. It seems obvious somewhere there is still a connection leak and that causes the error, but in a test with mock objects it doesn't seems possible to reproduce it. Maybe is there some stacktraces available?

**Comment by Marczeeee** [comment]
@davvd Please assign this task to someone else, I don't have any new ideas how to solve it. Hope someone will know it.

**Comment by davvd** [comment]
> @davvd Please assign this task to someone else, I don't have any new ideas how to solve it. Hope someone will know it.

@marczeeee right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@jenya This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@maurezen please go ahead with this task,it's yours

**Comment by davvd** [comment]
Closed, done, thanks all

**Comment by davvd** [comment]
my bad, closed by mistake

**Comment by maurezen** [comment]
@davvd please assign this issue to someone else.

**Comment by davvd** [comment]
> @davvd please assign this issue to someone else.

@maurezen right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by yegor256** [comment]
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
