### ISSUE TITLE
Unnecessary non-final variable bytes in HttpResponse.send()

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/s3auth#221]
In `HttpResponse.send()` we have the following code:

```java
            long bytes = 0L;
            bytes += this.body.writeTo(stream);
            return bytes;
```

What happens here is we're basically assigning the return value of `writeTo()` into `bytes` and then returning `bytes`. There's no need for a non-final variable `bytes`, why not return the value directly like so:

```java
            return this.body.writeTo(stream);;
```

**Comment by davvd** [comment]
@jenya you're holding this ticket for 9 days already. If it's not finished (and closed) in the next 1 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-5 added to your rating, at the moment it is: [-15](http://www.netbout.com/b/35092?open=rating)

**Comment by davvd** [comment]
@jenya you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 to your rating, your total score is [-435](http://www.netbout.com/b/35092?open=rating)

**Comment by davvd** [comment]
@maurezen the task is yours,please go ahead

**Comment by maurezen** [comment]
@davvd Created a pull request here #258

**Comment by maurezen** [comment]
@carlosmiranda pull request #258 merged, please close the issue.

**Comment by carlosmiranda** [comment]
@maurezen Perfect! Thank you, closing now.

**Comment by davvd** [comment]
@maurezen Thanks a lot, I just topped your account for **30 mins**, transaction ID `50570756`

added +30 to your rating, now it is equal to [+675](http://www.netbout.com/b/35102?open=rating)
