### ISSUE TITLE
Incomplete documentation: Exception logging

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/s3auth#226]
Specify in either
1. README.md or
2. src/site/notes.apt.vm

how the exceptions are supposed to be logged, ideally with an example like this:

```
public void someMethod()
{
    try
    {
        // Do something, which throws an exception
    }
    catch (Exception exception)
    {
        // Exception should be logged somewhere
    }   
}
```

**Comment by yegor256** [comment]
@dpisarenko  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
