### ISSUE TITLE
Every build seems to be downloading artifacts

### ISSUE THREAD

**Issue by darkled** [yegor256/s3auth#235]
When `maven` builds an application there are many log entries looking like

```
[INFO] Downloading: https://repo.maven.apache.org/...
[INFO] Downloaded: https://repo.maven.apache.org/... (12 KB at 612.2 KB/sec)
```

It seems there is no need to download artifacts every time build is running, local repository should be used instead.

**Comment by davvd** [comment]
@php-coder this task is not yours any more, please stop working with it (or ignore it if you haven't started yet), Thanks!

**Comment by davvd** [comment]
@marczeeee please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by Marczeeee** [comment]
@darkled Pull request #249 merged and closed. I think the issue can be closed.

**Comment by darkled** [comment]
@Marczeeee thanks, these log entries disappeared.

**Comment by davvd** [comment]
@marczeeee I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)

**Comment by Marczeeee** [comment]
@davvd I have no messages before but I created pull request #249 which was accepted as a solution for this task. So from my point of view I completed this task.

**Comment by yegor256** [comment]
@davvd please add extra 30 mins to @Marczeeee

**Comment by yegor256** [comment]
@Marczeeee for the future, when you complete a task, post pull request number where the issue was fixed, for traceability

**Comment by Marczeeee** [comment]
@yegor256 Sure, I'll pay more attention to this. Thank you!

**Comment by davvd** [comment]
> @davvd please add extra 30 mins to @Marczeeee 

@yegor256 I've sent 30 mins extra to @marczeeee in transaction ID "50308285"
