### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [yegor256/s3auth#247]
Copyright part in license sections still features 2014.

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@palyuga could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@maurezen thanks a lot for reporting, **15 mins** added to your acc, pmt ID `49961436`

**Comment by palyuga** [comment]
@maurezen PR #248 is merged, so we can close this issue

**Comment by davvd** [comment]
@palyuga Thanks for your contribution, **30 mins** was added to your account, payment ID is `50003454`

+30 to your rating, your total score is +75
