### ISSUE TITLE
HttpException.java:86-87: 1) Don't lose cause stacktrace...

### ISSUE THREAD

**Issue by davvd** [yegor256/s3auth#250]
Puzzle `198.-0764d06e` in `s3auth-relay/src/main/java/com/s3auth/relay/HttpException.java:86-87` has to be resolved: 1) Don't lose cause stacktrace 2) cause.getMessage can be null, so it can produce ConstraintViolationException instead of HttpException

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by nathansgreen** [comment]
@davvd okay, I opened ticket #252 and I'm waiting for someone to answer.

**Comment by yegor256** [comment]
@davvd we're waiting for #252 here

**Comment by davvd** [comment]
> @davvd we're waiting for #252 here

@yegor256 OK, let's wait for #252

**Comment by davvd** [comment]
The task is done, thanks all, I'm closing it

**Comment by davvd** [comment]
my bad, reopening

**Comment by yegor256** [comment]
@rultor deploy
