### ISSUE TITLE
Compiler error in com.s3auth.hosts.DefaultDynamoTest#loadsDynamoConfiguration

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/s3auth#255]
There is a compiler error in `com.s3auth.hosts.DefaultDynamoTest#loadsDynamoConfiguration`:

```
java: incompatible types: <anonymous com.s3auth.hosts.Dynamo.Client> 
cannot be converted to com.jcabi.dynamo.Credentials
```

Screenshot: http://i.imgur.com/nYcnYVq.png

I did `git pull` on my s3auth repository. According to Intellij Idea, the contents of that file is the same as in the master repository.

Please tell me, how I can fix this problem with least effort.

**Comment by yegor256** [comment]
looks like an issue with IntelliJ. try to clean its cache and restart. if the problem is not reproducible from command line, we can't fix it.

**Comment by dpisarenko** [comment]
This didn't help. I'll try to do a new checkout of s3auth.
