### ISSUE TITLE
Incomplete documentation: LocalHost.isIt()

### ISSUE THREAD

**Issue by asaen** [yegor256/s3auth#257]
For the moment method `com.s3auth.relay.LocalHost.isIt(String)` with its documentation looks pretty confusing:

``` java
/**
 * Is it your name?
 * @param name The name of host, provided in "Host" HTTP header
 * @return TRUE if this is a localhost
 */
public static boolean isIt(@NotNull final String name) {
    return "relay.s3auth.com".equals(name);
}
```

Instinctively, it should compare `name`against `"localhost:..."`. Therefore it looks like something in the javadoc missed. What is the real purpose to have such method and what is `"relay.s3auth.com"`?

**Comment by yegor256** [comment]
@davvd I'll fix this, assign me to this problem pls

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by davvd** [comment]
> @davvd I'll fix this, assign me to this problem pls

@yegor256 the task is yours, please proceed

**Comment by davvd** [comment]
@darkled thanks for tis bug, I topped your account for 15 mins, transaction `50349631`

**Comment by longtimeago** [comment]
@yegor256 any progress here?

**Comment by darkled** [comment]
@yegor256 do you have any news here?

**Comment by davvd** [comment]
@darkled I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 right, I will find someone else, no problem

**Comment by darkled** [comment]
it's not actual anymore, closing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
