### ISSUE TITLE
How to implement #213

### ISSUE THREAD

**Issue by pinaf** [yegor256/s3auth#262]
Issue #213 requests an FTP frontend for downloading files, analogous to the current HTTP frontend. Implementation would be based on creating a new class, `FTPFacade`, analogous to the existing `HTTPFacade`.

However, the following items are not clear in the request for the new functionality:
1. Should the FTP server be implemented through an existing Java library or should it create a raw socket and parse (which seems to be what `HTTPFacade` does)?
2. What port should the FTP server listen on?
3. What FTP verbs should be supported (OPEN, USER, LIST, CD, RETR)?
4. When the client is behind a firewall, FTP usually goes to Passive mode. Is this to be implemented also?
4. What about security (SSL)?

**Comment by yegor256** [comment]
@pinaf check this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken When you report a bug you should say what is broken now. I think in this case a README file is broken since it doesn't explain how our service provides FTP. Right?

**Comment by pinaf** [comment]
@yegor256  Well I'm asking for more information on how to implement a feature that doesn't exist yet. Is that considered a bug? I don't see why the README file should carry this type of information. Maybe this file http://maven.s3auth.com/architecture.html ?

**Comment by yegor256** [comment]
@pinaf maybe this file, but it has to be a bug. Everything you submit to a project should be formatted as a bug. By submitting a bug you disturb the project and by fixing it we're getting the project back to a stable state. This section of the article should explain better: http://www.yegor256.com/2014/04/12/puzzle-driven-development-by-roles.html#fix-and-break

So, every time you need information - find out who fails to provide it to you at the moment. And complain about him (javadoc, readme, html, etc)

**Comment by pinaf** [comment]
@yegor256 Ok so I should be doing a little bit of breaking here - that is what I'm trying to do. From the article it seems to me the project manager would be responsible for `unclear or ambiguous requirements` - so I should complain to davvd the request is not clear?

**Comment by yegor256** [comment]
@pinaf I don't think so. In this case, you are starting to implement a new feature. There is no help for you here from the management side. You're in the position of an architect/designer here. See http://www.yegor256.com/2014/04/12/puzzle-driven-development-by-roles.html#architect

Your complaints/bugs should be addressed to the existing design documentation.

**Comment by pinaf** [comment]
@yegor256 Hmmm.. and the complaints should be addressed in the form of puzzels I suppose?

**Comment by yegor256** [comment]
@pinaf if you have no idea where to start, it's a bug (a new ticket). If you know how to create a high level design but don't know what to do next, it's a pull request with puzzles inside.

**Comment by pinaf** [comment]
@yegor256 I think I got it. Let me digest it a bit more :) thanks!
