### ISSUE TITLE
pdd check missing from travis

### ISSUE THREAD

**Issue by krzyk** [yegor256/s3auth#265]
Travis configuration in `script` is missing
```
  - gem install pdd                                                                                                                                           
  - pdd --file=/dev/null
```
which exists in rultor config.
It would be better to have it in travis so the errors in puzzle formats could be found earlier.

**Comment by krzyk** [comment]
ping

**Comment by yegor256** [comment]
@krzyk I fixed Travis config in 208824e

**Comment by davvd** [comment]
@yegor256 please don't close it.. @krzyk could you please close it, if it is done?

**Comment by krzyk** [comment]
thanks
