### ISSUE TITLE
Files in subdirectories return s3auth auto-generated page rather than actual content.

### ISSUE THREAD

**Issue by rygo6** [yegor256/s3auth#269]
Any file in a subdirectory that I access through s3auth returns the page that s3auth auto generates, rather than the actual content. So if I try to access images/me.jpg I get back a page saying 'This is an auto generated page" and it shows the path to the file. It does not do this for any files in the root. Any ideas on why this might be and how I could correct it?

**Comment by yegor256** [comment]
@rygo6 are you sure? take a look at this file: http://maven.s3auth.com/apidocs/index.html It works well

**Comment by yegor256** [comment]
@rygo6 looks like in your case you're either giving wrong names of the files, or that files are not accessible by IAM user

**Comment by yegor256** [comment]
@rygo6 This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
