### ISSUE TITLE
How to run it locally ?

### ISSUE THREAD

**Issue by Azulinho** [yegor256/s3auth#270]
I am able to build this using:

mvn -Dmaven.test.skip=true clean install

But how do I run it ?

(thanks for coding it)

**Comment by Azulinho** [comment]
I am able to build this using:

mvn -Dmaven.test.skip=true clean install

But how do I run it ?

(thanks for coding it)

**Comment by tonymet** [comment]
```
cd s3auth-rest; java -Xmx512m -XX:MaxPermSize=128m -cp target/s3auth-rest.jar:target/s3auth-rest/WEB-INF/lib/* com.s3auth.Launch
```

**Comment by tonymet** [comment]
```
 cd s3auth-rest; PORT=3030 java -Xmx512m -XX:MaxPermSize=128m -cp target/s3auth-rest.jar:target/s3auth-rest/WEB-INF/lib/* com.s3auth.Launch
```

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Azulinho explained in 525a9c2 Looks good? Works? If yes, please close the ticket

**Comment by Azulinho** [comment]
good stuff
