### ISSUE TITLE
Error removing individual host from s3auth.com profile

### ISSUE THREAD

**Issue by trystant** [yegor256/s3auth#272]
Hi,

I'm logged in as trystant to s3auth.com and am trying to remove http://patriciawrightlaw.grandkru.com from my profile. For some reason, the host is not deleted. How can I delete that host? Thanks.

**Comment by yegor256** [comment]
@trystant what happens when you're clicking "delete"?

**Comment by trystant** [comment]
Hi @yegor256,

This is the message I get
![screenshot 2015-03-12 00 17 26](https://cloud.githubusercontent.com/assets/13509/6612175/7b0499e0-c84d-11e4-9770-ba1adc38eb1a.png)

**Comment by yegor256** [comment]
@trystant yes, I see the problem, I also can't delete a domain from my account. thanks for reporting, we'll take care of this soon!

**Comment by davvd** [comment]
I will find a developer for the task soon...

**Comment by pilotlab** [comment]
I am having the same issue as well for studies.pilotlab.com. I get a confirmation that it has been removed but the site remains on the list of registered domains and continues to give a the authentication prompt.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@trystant I believe it works fine now, please check

**Comment by davvd** [comment]
@trystant there is no milestone yet, so I set it to `1.0`

**Comment by yegor256** [comment]
@trystant This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
