### ISSUE TITLE
Cannot delete existing registered domains

### ISSUE THREAD

**Issue by nicelemon** [yegor256/s3auth#282]
When adding a new domain I entered the bucket name incorrectly, and now it seems that I'm unable to delete or edit the record. Here's the error I get when I attempt to delete the record:

> Application Error

> An error occurred in the application and your page could not be served. Please try again in a few moments.

> If you are the application owner, check your logs for details.

After refresh it says the record was deleted, however the record persists and I'm unable to add a new record with the same host name.

**Comment by nicelemon** [comment]
I'd love to use your service, but I'm still experiencing the following error when attempting to delete an existing entry:

![screen shot 2015-04-03 at 2 04 48 pm](https://cloud.githubusercontent.com/assets/6396220/6986404/e5a820d6-da0a-11e4-939b-2fe6f01418eb.png)

After refreshing the page I see the following even though the entry persists:

![screen shot 2015-04-03 at 2 06 43 pm](https://cloud.githubusercontent.com/assets/6396220/6986726/13135060-da0e-11e4-8e2a-29ffb1ee46a0.png)

Any help would be greatly appreciated.

**Comment by yegor256** [comment]
@nicelemon it's a known bug, I'm working on it and planning to fix on this weekend, see https://github.com/yegor256/s3auth/issues/272

**Comment by nicelemon** [comment]
@yegor256 Sorry I missed this. Thanks for the reply!
