### ISSUE TITLE
qulice fails on .DS_store files

### ISSUE THREAD

**Issue by rygo6** [yegor256/s3auth#283]
I’ve been working on a feature to put into s3auth that I need. I have come to the point where I ran qulice on the project for the first time and it came back with errors about DS_store files. Which seemed odd to me that ignores aren’t already on the repo for that, I was then going to put in excludes for DS_store files as per this page describes:
http://www.qulice.com/qulice-maven-plugin/example-exclude.html

But then after copying this around in the pom.xml

```
<exclude>checkstyle:.DS_store</exclude>
<exclude>pmd:.DS_store</exclude>
<exclude>findbugs:.DS_store</exclude>
<exclude>codenarc:.DS_store</exclude>
<exclude>dependencies:.DS_store</exclude>
<exclude>cobertura:.DS_store</exclude>
<exclude>jslint:.DS_store</exclude>
<exclude>duplicatefinder:.DS_store</exclude>
```

I thought, that is quite ugly, and can’t possibly be correct. Since that isn’t already done it either means one of two things. 
1. No one at teamed.io has ever ran qulice on OSX, which I presume is unlikely. Which leads me to, 
2. Putting in excludes for the .DS_store is completely the wrong way to go about this. 

So, I thought I’d ask. Does no one at teamed.io use OSX? Or is there a more ideal way to deal with the DS_store file issue that is precluding me?

**Comment by yegor256** [comment]
@rygo6 I'm working on OSX, but I never have `.DS_Store` files in the repo. Are you opening the directory with Finder??

BTW, who is complaining about that file? Can you should the log?

**Comment by rygo6** [comment]
These are the errors.

    [ERROR] /src/main/.DS_Store[1]: Line has trailing spaces. (RegexpSinglelineCheck)
    [ERROR] /src/main/.DS_Store[2]: Line has trailing spaces. (RegexpSinglelineCheck)
    [ERROR] /src/main/.DS_Store[3]: Line has trailing spaces. (RegexpSinglelineCheck)
    [ERROR] /src/site/.DS_Store[1]: Line has trailing spaces. (RegexpSinglelineCheck)
    [ERROR] /src/site/.DS_Store[2]: Line has trailing spaces. (RegexpSinglelineCheck)
    [ERROR] /src/site/.DS_Store[3]: Line has trailing spaces. (RegexpSinglelineCheck)

Which is from me going into the directory with finder. 

If never going into the directory with finder is the preferred method, I am perfectly fine with that. Just wanted to be sure I wasn't missing something important, like some global flag on qulice to ignore these files.

**Comment by yegor256** [comment]
@rygo6 just don't touch the directory with Finder. These complaints are coming from Checkstyle, so just this exclusion will be enough:

```
<exclude>checkstyle:.*/.DS_store</exclude>
```

(it's a regex)

**Comment by yegor256** [comment]
@rygo6 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
