### ISSUE TITLE
keep getting "Application Error" at http://www.s3auth.com

### ISSUE THREAD

**Issue by Masabu** [yegor256/s3auth#295]
Hi

I keep getting "Application Error" when I try to fix/remove my existing entry.  My amazon AWS credential changed so I am trying to update the entry however when I remove it, i get the message removed 'xxxx.com' host from collection but it actually does not remove the entry.

am accessing via http://www.s3auth.com

**Comment by yegor256** [comment]
it's a known bug, I'm going to fix it today or tomorrow the latest, see https://github.com/yegor256/s3auth/issues/272

**Comment by davvd** [comment]
@masabu I will find a developer for the task soon...

**Comment by Masabu** [comment]
thanks, looking forward!!

**Comment by yegor256** [comment]
@Masabu I think it's fixed, please check

**Comment by davvd** [comment]
@masabu It is "invalid", I am closing it
