### ISSUE TITLE
migrate to takes 0.12

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#296]

**Comment by davvd** [comment]
@yegor256 this is yours, pls go ahead

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-16b6cb61`

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@yegor256 thanks, paid, **45 mins** to your account, payment ID is `000-1dbc391b`, task took 70 hours and 22 mins to complete... the bonus for fast delivery (age=1476)... +45 to your rating, your total score is [+9062](http://www.netbout.com/b/35008?open=rating)
