### ISSUE TITLE
Keeps asking for Authentication

### ISSUE THREAD

**Issue by ajayrn** [yegor256/s3auth#303]
Hi, 
i did the following and when I go to test.mydomain.info i keep getting authentication requests but even when I give correct user name and password, it doesn't work. 
1. Created a bucket mydomain.info in S3. It also has index.html
2. Then I used route 53 to make the s3 domain a custom domain called mydomain.info 
3. I pointed CNAME DNS of mydomain.info i.e. test.mydomain.info to relay.s3auth.com 
4. Now I created a IAM user with the custom policy. 
5. I gave test.mydomain.info as the host name, IAM user's access key and secret key and registered the domain at  s3auth website. I gave the bucket name as mydomain.info  
6. I created the .htpasswd file using notepad (saved it as .htpasswd) and uploaded it to mydomain.info where my index.html also resides 
7. when i try to access test.mydomain.info it keeps asking me for password. I tried changing the passwords several times but it wouldn't let me in. 
8. I also tried http://test.mydomain.info/.htpasswd and it displays the number of bytes as it should. 

so I am kind of lost about how to solve this issue.

**Comment by yegor256** [comment]
@ajayrn my first guess is that you're using a wrong login/password. Are you sure you created the `.htpasswd` correctly?

**Comment by ajayrn** [comment]
I used the online tool. It looks like,
name: encrypted password
I saved it to the root as user.htpasswd

**Comment by ajayrn** [comment]
It worked. I renamed the user.htpasswd file to simply .htpasswd and it worked :)
