### ISSUE TITLE
beginner question - see www.s3auth.com

### ISSUE THREAD

**Issue by mamuemi** [yegor256/s3auth#304]
hey,
i've read about s3auth.com and immediately liked the idea to secure my "AWS S3 static website hosting". unfortunately, i had to give up after not getting beyond the message "see www.s3auth.com" when call the website URL provided by AWS S3 static hosting. 
Since the html request for myDomiain.com/.htpasswd also didn't work, I am just wondering what went wrong. i've double-checked the IAM custom policy, the .htpasswd and all seems fine to me.
any guidance? 
thanks,
    marius

**Comment by yegor256** [comment]
@mamuemi what do you see when you open `mydomain.com/.htpasswd`?

**Comment by mamuemi** [comment]
my domain: muemi-test.s3-website.eu-central-1.amazonaws.com
routing to: http://relay.s3auth.com/

that's what is shown when I type in 'muemi-test.s3-website.eu-central-1.amazonaws.com' (routing to 'http://relay.s3auth.com/.htpasswd'): URI '/.htpasswd' not found here

iam policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": ["s3:ListBucket"],
            "Resource": ["arn:aws:s3:::muemi-test"]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetBucketWebsite"
            ],
            "Resource": [
                "arn:aws:s3:::muemi-test/*"
            ]
        }
    ]
}

**Comment by yegor256** [comment]
@mamuemi I don't think you can route `muemi-test.s3-website.eu-central-1.amazonaws.com` anywhere :) it's in amazonaws.com domain

**Comment by mamuemi** [comment]
that would explain it, but I am confused that the muemi-test.s3-website.eu-central-1.amazonaws.com route to your service: http://relay.s3auth.com/
i don't have another domain to use since i only like to simply, quickly have secured access to my s3 bucket via the browser :-) probably, i have to look for something else then.
thanks for you help though!

**Comment by yegor256** [comment]
@mamuemi 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
