### ISSUE TITLE
@NotNull annotations are inconsistently used

### ISSUE THREAD

**Issue by simonjenga** [yegor256/s3auth#309]
There are many classes that have ```constructors``` and ```methods``` whose arguments/parameters are annotated with ```@NotNull```, and also some other ```constructors``` and ```methods``` that don't have those annotations.

This is especially true in the ```package com.s3auth.hosts``` although a thorough revision of the entire project Java source files needs to be done.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga even though it's a valid concern, there is no valid way to solve this problem. We can go through the entire code base and add that annotations, but tomorrow someone will forget to put it to some new method, and the project will get back to inconsistent state. So, we should leave it as is :(
