### ISSUE TITLE
unnecessary method call in com.s3auth.hosts.Domains#get(String)

### ISSUE THREAD

**Issue by simonjenga** [yegor256/s3auth#316]
Why do we need to call `com.s3auth.hosts.Domains#this.has(name)` in the current implementation of `com.s3auth.hosts.Domains#get(String)`. The `if (this.has(name))` check is not needed.

It's kind of a circular logic; you are first checking if it exists using `this.has(name)` and then you are performing another operation to retrieve it using `this.all.get(name)`.

```
public Domain get(@NotNull final String name) {
    Domain found = null;
    if (this.has(name)) {
        found = this.all.get(name);
    } else {
        throw new IllegalArgumentException(
            String.format("domain %s not found", name)
        );
    }
    return found;
}
```

Can't we simplify it to be as follows?

```
public Domain get(@NotNull final String name) {
    Domain found = this.all.get(name);
    if (found == null) {
        throw new IllegalArgumentException(
            String.format("domain %s not found", name)
        );
    }
    return found;
}
```

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://www.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@simonjenga feel free to submit a pull request, sounds like a valid concern, thanks.

**Comment by simonjenga** [comment]
@yegor256 Sure, will do it soon...

**Comment by simonjenga** [comment]
Done!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
