### ISSUE TITLE
upgrade to jcabi-parent 0.49.3

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#317]
Let's upgrade to `jcabi-parent` version 0.49.3 and make sure it still works.

**Comment by 0crat** [comment]
Job [#317](https://github.com/yegor256/s3auth/issues/317) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#317](https://github.com/yegor256/s3auth/issues/317) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C3RP1J1CH/861064007); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting for review on PR #370

**Comment by 0crat** [comment]
> @0crat waiting for review on PR #370 ([here](https://github.com/yegor256/s3auth/issues/317#issuecomment-378277095))

@llorllale The impediment for [#317](https://github.com/yegor256/s3auth/issues/317) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#371](https://github.com/yegor256/s3auth/issues/371) is still not solved.

**Comment by llorllale** [comment]
@yegor256 ping!

Can we close this issue?

**Comment by yegor256** [comment]
@llorllale thanks

**Comment by 0crat** [comment]
The job [#317](https://github.com/yegor256/s3auth/issues/317) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#unknown]() is solved here.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#371](https://github.com/yegor256/s3auth/issues/371) is solved here.
