### ISSUE TITLE
Files with ampersand & in the name crash the output.

### ISSUE THREAD

**Issue by oblodgett** [yegor256/s3auth#325]
Filename: 214B - Changing the Word Part 1, 2 & 3.mp4
Cause the follow error in the output page:

This page contains the following errors:
error on line 151 at column 127: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.

Quick fix rename your file.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by oblodgett** [comment]
Yes... I just tried it, and it works fine. Sorry didn't close this before now, thanks again.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
