### ISSUE TITLE
Some questions about the service

### ISSUE THREAD

**Issue by johnccfm** [yegor256/s3auth#327]
Hi-

I've managed to get the service working with my bucket, but I have a few questions that I can't find answers to.

- Does the system require the Static Web Site feature of the bucket to be enabled, or does it access the bucket contents via the REST API?
- I've probably granted way more permissions than needed in my policy and will try to cut them down, but how can s3auth generate the index listings without a ListBucket permission?
- Is there any way to prevent the **.htpasswd** file showing in the generated index of the root of the bucket?
- What kind of things will the system send to the logging server? I was hoping for access logs, but so far I've not seen anything at all.
- Is it possible to limit the receipt of logging packets on my log server by source IP? If so, what IPs should I use?

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@johnccfm it does access the content via AWS REST API. ListBucket is required to generate the listing. there is not way to hide `.htpasswd` in the listing, but its content won't be rendered ever. logging (syslog) doesn't work at the moment.

**Comment by yegor256** [comment]
@johnccfm if all questions are answered, please close the ticket
