### ISSUE TITLE
s3auth Internal application error. 

### ISSUE THREAD

**Issue by mikecarr55** [yegor256/s3auth#328]
I created a at s3auth.com but wanted to edit it so I submitted it again. then got the Internal application error. so I deleted my domain and tried again but still get the error when trying to submit. can anything be done?

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@mikecarr55 sure, what exactly do you see when you're trying to submit? what does the error page say?

**Comment by mikecarr55** [comment]
well this time it did not throw the error - thank you

now I just have to figure out why it gets stuck in the login loop -

I attached inline policy in IAM for user s3blue:

{
     "Statement": [
         {
             "Effect": "Allow",
             "Action": [
                 "s3:GetObject",
                 "s3:GetBucketWebsite"
             ],
             "Resource": [
                 "arn:aws:s3:::s3.blue.thickdata.com/*"
             ]
         }
     ]
}


then I created 2 users and passwords at aspirine.org using MD5 hash -

:user :pass
mikecarr zorkon4!
blueuser Eleven_232

generated file
mikecarr:$apr1$D7VWJant$tg5Vdj/AT4/WzDs70VJOL0
blueuser:$apr1$WzcU1j7P$.q8fz4JopeVolVMCLrlaY/

uploaded file to bucket root

http://s3.blue.thickdata.com/.htpasswd shows 26099 byte(s)

**Comment by yegor256** [comment]
@mikecarr55 you are still experiencing this problem?

**Comment by mikecarr55** [comment]
sorry, I never got it to work so I gave up



Michael Carrington

**Comment by yegor256** [comment]
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
