### ISSUE TITLE
better error message then "invalid host name"

### ISSUE THREAD

**Issue by mdagit** [yegor256/s3auth#337]
in com.s3auth.hosts.DynamoHosts how about instead of "invalid host name" a clearer
error message like "hostname contains characters not allowed by RFC1123" .
Because otherwise are going to think it is a resolver error, not a name syntax error.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@mdagit fixed, thanks!
