### ISSUE TITLE
README says mvn clean install -Pqulice but it doesn't work

### ISSUE THREAD

**Issue by mdagit** [yegor256/s3auth#338]
I just did a fresh checkout and normal "mvn clean install -DskipTests=true" works fine,
but the profile qulice does not:

```
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html)
[INFO] Existing cacerts '/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/security/cacerts' copied to '/Users/mda/home2/projectwds/s3auth/target/cacerts.jks' (53 bytes)
[INFO] jcabi-aspects 0.20.1/f0aff93 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[ERROR] #genkey(): thrown java.util.MissingResourceException(Can't find resource for bundle sun.security.util.Resources, key yes) out of java.util.ResourceBundle#getObject[450] in 83ms
[ERROR] #activate(/Users/mda/home2/projectwds/s3auth/target/keystore.jks): thrown java.util.MissingResourceException(Can't find resource for bundle sun.security.util.Resources, key yes) out of java.util.ResourceBundle#getObject[450] in 89ms
```

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@mdagit this is really something weird. Can you try to run again?

**Comment by mdagit** [comment]
same deal:

mvn clean install  -Pqulice
[INFO] Scanning for projects...
...

[INFO] --- jcabi-ssl-maven-plugin:0.11:keygen (default) @ s3auth ---
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html)
[INFO] Existing cacerts '/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/security/cacerts' copied to '/Users/mda/home2/projectwds/s3auth/target/cacerts.jks' (53 bytes)
[INFO] jcabi-aspects 0.20.1/f0aff93 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[ERROR] #genkey(): thrown java.util.MissingResourceException(Can't find resource for bundle sun.security.util.Resources, key yes) out of java.util.ResourceBundle#getObject[450] in 36ms
[ERROR] #activate(/Users/mda/home2/projectwds/s3auth/target/keystore.jks): thrown java.util.MissingResourceException(Can't find resource for bundle sun.security.util.Resources, key yes) out of java.util.ResourceBundle#getObject[450] in 43ms
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] s3auth ............................................. FAILURE [  1.341 s]

**Comment by yegor256** [comment]
@mdagit @jart I'm sorry this bug is still not fixed. We didn't have enough funds/time to work on the project. However, recently we received some donations from our grateful users and will continue to fix issues and introduce new features. Would be great if you can also donate -- to help us move forward faster. Here is the link: https://www.0crat.com/contrib/C3RP1J1CH

**Comment by yegor256** [comment]
@mdagit This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution! The build works for me, Java 8.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
