### ISSUE TITLE
troubleshooting instructions in s3auth-rest/src/main/xsl/index.xsl don't make sense

### ISSUE THREAD

**Issue by mdagit** [yegor256/s3auth#339]
btw, the static content really shouldn't be in the xsl templates right?
but in some other file that is more directly findable and editable?

Anyway, the troubleshooting instructions in s3auth-rest/src/main/xsl/index.xsl
don't make much sense to me. I guess "joe" is a record that is supposed to be in the .htpasswd file?
And maven.s3auth.com should instead be whatever my CNAME record is?
But why should asking for an index.html file tell me anything about the content of the .htpasswd
file?
I tried it, and if the index.html doesn't exist, i get back an exception,
java.io.IOException: failed to fetch /index.html 
and if the index.html does exist, it simply returns the contents in that file, as I would expect --
nothing about the .htpasswd file.

Or maybe you really mean maven.s3auth.com and i should use not a .htpasswd user,
but my github s3auth.com account? but then how is that supposed to work, since that is OAuth2?

thanks.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@mdagit too many questions in one ticket :) Let's start with the first one and fix it. What is the first question/bug?

**Comment by mdagit** [comment]
Basically that the index.xsl examples/instructions need more explanation. Which of those things are literal values and which are symbolic? What is "joe"? a github account or a .htpasswd account?
What is maven.s3auth.com ? A literal value, or our CNAME, or what?
