### ISSUE TITLE
s3auth responds with error when aws cloudfront custom error page is enabled

### ISSUE THREAD

**Issue by oviwankenobi** [yegor256/s3auth#341]
According to AWS, You can configure CloudFront to respond to requests using a custom error page when your origin returns an HTTP 4xx or 5xx status code. For example, when your custom origin is unavailable and returning 5xx responses, CloudFront can return a static error page that is hosted on Amazon S3.

I did that, while I have the s3auth set up (which works great without cloudfront enabled for my website) but when I enable cloudfront to respond with index.html when 4xx and 5xx happens I get the below error message from s3auth (e.g. when accessing www.mysite.com/nonexistingpage) 

"This is page is auto-generated by s3auth.com.
The prefix is: asdasdsdfds/
Name    Size (bytes)"

any idea how to investigate this? or what is going on?

p.s. www.mysite.com/existingpage works well

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by OviWanKenoby** [comment]
I think I got confused on this matter and our setup was done wrong, in such way that s3auth was bypassing the cloudfront, so basically it had nothing to do with the cloudfront.I think we can close this. 
thank you

**Comment by oviwankenobi** [comment]
I think I got confused on this matter and our setup was done wrong, in such way that s3auth was bypassing the cloudfront, so basically it had nothing to do with the cloudfront.I think we can close this. 
thank you
