### ISSUE TITLE
root directory of a bucket isnt showing

### ISSUE THREAD

**Issue by lulatsch0** [yegor256/s3auth#343]
Hello,
i have an issue with my s3auth and my bucket.
The root directory contains the .htpasswd file and two folders which contains the files.
When i open the root directory, i get a blank page and the browsertitle begins with </head> <body>. But i cant see the two folders.
But when i open the folder directly .../folder, the content will show correctly.
In the past, it was also works with the root directory.

What is wrong?

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@lulatsch0 this was a bug, thanks for reporting. It's fixed already.
