### ISSUE TITLE
invalid header line: 'AlexaToolbar-ALX_NS_PH: AlexaToolbar/alx-4.0'

### ISSUE THREAD

**Issue by mgriba** [yegor256/s3auth#345]
Receiving the above message on certain domains only it seems and only from IE browsers.  Chrome works fine.  Firefox untested so far.

Any idea what this is related to?

Thank you,

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@mgriba well, this header line is indeed invalid. This is the pattern it is matched against: https://github.com/yegor256/s3auth/blob/master/s3auth-relay/src/main/java/com/s3auth/relay/HttpRequest.java#L107 You think the pattern is not valid?

**Comment by mgriba** [comment]
Ah I see the issue then I believe.  The problem is the encryption I used on the htpasswd file (MD5).  It defaulted to the wrong one on the aspirine.org page.  I need to regenerate as SHA1 it appears.  But, it does still work through Chrome with the invalid header type.  Am I looking at this correctly?

Thank you,

**Comment by yegor256** [comment]
@mgriba I don't really know what's going on... But the header above is not a valid HTTP header. Please, submit a new ticket for other problems you are experiencing, if any.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
