### ISSUE TITLE
Return code is: 405, ReasonPhrase: Method Not Allowed.

### ISSUE THREAD

**Issue by tmoreira2020** [yegor256/s3auth#347]
Hi there, I'm trying to upload snapshot packages to a brand new configuration but I'm getting the following error

`Return code is: 405, ReasonPhrase: Method Not Allowed.`

I'm able to browse without problem the repository. The credentials used to configure s3auth.com are associated to a user that has full access (AmazonS3FullAccess) to S3.

Not sure what else I need to do to be able to upload packages!

Thanks

**Comment by Ralphilius** [comment]
This is not possible if you want to upload to S3 with s3auth.com since the PUT API requires more credentials data. You can use `maven-publish` plugin if you want to upload your artifacts.

**Comment by yegor256** [comment]
@tmoreira2020 the answer of @ralphilius is correct, you can't upload anything, s3auth.com is read-only.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
