### ISSUE TITLE
S3 bucket policy to set everything to private

### ISSUE THREAD

**Issue by ismaelc** [yegor256/s3auth#349]
Hi. Do you have a sample bucket policy that sets all objects to private but lets s3auth access? There used to be a "set to private" option in the admin console but can't seem to find it anymore. Been trying out a couple of bucket policies to set objects to private but to no avail. Hope you can help.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by ismaelc** [comment]
Actually my problem is that the login prompt isn't kicking in when accessing the raw S3 bucket. It only shows when accessing via custom domain.

**Comment by yegor256** [comment]
@ismaelc by default all objects are private, unless you explicitly make them public and they will become available via API (not through HTTP). So, I guess you're on the wrong way. Can you please explain better?

**Comment by yegor256** [comment]
@ismaelc 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
