### ISSUE TITLE
DefaultDynamoTest.java:61-64: This test creates a mock region with...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/s3auth#352]
The puzzle `90-43f9c549` in [`s3auth-hosts/src/test/java/com/s3auth/hosts/DefaultDynamoTest.java`](https://github.com/yegor256/s3auth/blob/master/s3auth-hosts/src/test/java/com/s3auth/hosts/DefaultDynamoTest.java) (lines 61-64) has to be resolved: This test creates a mock region with a H2Data backend which has table columns with characters unsupported by the h2 database. Issue #7 in jcabi-dynamo should fix this. Don't forget to remove the @Ignore annotation from this test.

The puzzle was created by pinaf on 20-Jan-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `90-43f9c549` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/s3auth#352` is not assigned, can't get performer
