### ISSUE TITLE
RendersHomePage.js:33-33: Migrate old tests from rexsl/scripts...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/s3auth#354]
The puzzle `200-e1abb509` in [`s3auth-rest/src/test/casperjs/RendersHomePage.js`](https://github.com/yegor256/s3auth/blob/master/s3auth-rest/src/test/casperjs/RendersHomePage.js) (lines 33-33) has to be resolved: Migrate old tests from rexsl/scripts to casperjs

The puzzle was created by unknown on 14-Dec-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `200-e1abb509` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/s3auth#354` is not assigned, can't get performer
