### ISSUE TITLE
Licence link on http://www.s3auth.com/ is broken

### ISSUE THREAD

**Issue by Synesso** [yegor256/s3auth#361]
1. go to http://www.s3auth.com/
2. click on LICENCE.txt
3. Page displays message - "Sorry, this page is absent."

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@Synesso fixed, thanks for reporting!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/s3auth#361` was not in scope
