### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by eligiable** [yegor256/s3auth#362]
Hi There
What are the steps to run it? No Wiki ...

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by eligiable** [comment]
` Failure to transfer joda-time:joda-time/maven-metadata.xml from s3://repo.s3auth.com/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of repo.s3auth.com has elapsed or updates are forced. Original error: Could not transfer metadata joda-time:joda-time/maven-metadata.xml from/to repo.s3auth.com (s3://repo.s3auth.com/snapshot): Could not connect to repository`

This is the error and it does not move ahead

**Comment by eligiable** [comment]
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (casperjs-test) on project s3auth-rest: Command execution failed. Process exited with an error: 127 (Exit value: 127)

**Comment by yegor256** [comment]
@eligiable what exactly are you trying to achieve?

**Comment by eligiable** [comment]
@yegor256 I'm trying to run it locally.

**Comment by yegor256** [comment]
@eligiable just for fun? Or you want to host it somewhere?

**Comment by eligiable** [comment]
@yegor256 Its not for fun, we have a lots of files need to be synced to s3, and need to created multiple users to access via Web.

**Comment by yegor256** [comment]
@eligiable use www.s3auth.com  It is created just for this purpose.

**Comment by eligiable** [comment]
@yegor256 I've tested this and its a great service, but the issue is, I've to redirect twice the CNAME to get to s3auth from Amazon, I already have domain and subdomain to re direct to instead of using s3 long url and sometimes the cookies expires and the s3auth url does not work, because of multiple CNAME.

This is why I would like to host my own and not to register a domain on s3.

**Comment by yegor256** [comment]
@eligiable how come "the s3auth URL does not work, because of multiple CNAME." I didn't get it? Please explain.

**Comment by yegor256** [comment]
@eligiable This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!
