### ISSUE TITLE
getting access denied from s3auth, but can access full path files

### ISSUE THREAD

**Issue by gsiegfried** [yegor256/s3auth#363]
Recently set up s3auth, as instructed.  The basic auth dialog comes up, but once the password is entered, a stack trace is sent back as follows:
java.io.IOException: failed to fetch / from 'bucket' (key=KEY): ["'+suffix': Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 75925EDF0A79385A)", "'+suffix': Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: C23428BA0EF98881)"]

[key and bucket name removed]
bucket is in Ohio, I have tried with and without the Ohio endpoint specified in the s3Auth configuration.
Once I authenticate, and the stacktrace is displayed, I can enter the name of a file in the root of the bucket and can access it.

Advice appreciated!

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@gsiegfried looks like you didn't configure the permission for the bucket. We simply can't fetch the `index.html` from there.

**Comment by yegor256** [comment]
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by TXAHUB** [comment]
I am having the exact same issue on the same server
