### ISSUE TITLE
Single-page applications

### ISSUE THREAD

**Issue by graemecode** [yegor256/s3auth#372]
Firstly, thanks for this awesome tool.

Using the nifty setup at http://www.s3auth.com, I've successfully set up a private demo of my app. However, since it's a single-page application, I'd love for all routes (e.g. `/dashboard`, `/request`) to load my react app at index.html, which has its own router. 

Is there any way I could configure my current setup, such that this happens instead of trying to locate a `dashboard` bucket, etc., in s3?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@graemecode[/z](https://www.0crat.com/u/graemecode) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RP1J1CH) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@graemecode it's not possible. The best solution would be to create `dashboard`, `request` files in your bucket and make them do JavaScript redirect on load: https://stackoverflow.com/questions/503093/how-do-i-redirect-to-another-webpage
