### ISSUE TITLE
Update jcabi-parent to 0.49.4 (solves xcop issue)

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/s3auth#376]
Let's update to new jcabi version (0.49.4) because this new version solves xcop issue on windows.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RP1J1CH) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@fabriciofx fixed

**Comment by 0crat** [comment]
Job `gh:yegor256/s3auth#376` is not assigned, can't get performer
