### ISSUE TITLE
migrate to Dokku

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#379]

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/s3auth#379` is not assigned, can't get performer
