### ISSUE TITLE
Is s3auth.com down?

### ISSUE THREAD

**Issue by dylanic-dev** [yegor256/s3auth#381]
I believe s3auth.com domain has disappeared?

**Comment by dylanic-dev** [comment]
back up again now.
s3auth.com. IN NS
;ANSWER
s3auth.com. 21599 IN NS ns-1118.awsdns-11.org.
s3auth.com. 21599 IN NS ns-1854.awsdns-39.co.uk.
s3auth.com. 21599 IN NS ns-449.awsdns-56.com.
s3auth.com. 21599 IN NS ns-756.awsdns-30.net.
;AUTHORITY

**Comment by DrCord** [comment]
seem to be a site called ReHTTP now, no way to register a site for s3auth.

**Comment by vivekiyer87** [comment]
what about the sites that were registered..

**Comment by s1mrankaur** [comment]
seems to be down again

**Comment by yegor256** [comment]
@s1mrankaur working on it...

**Comment by jiri-kovarik** [comment]
relay.s3auth.com is timing out atm, could this be related?

**Comment by yegor256** [comment]
@DrCord should be up and running now again, please check
