### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by CherryDT** [yegor256/s3auth#405]
Sites that are directed to `relay.s3auth.com` are timing out, and it's [not just me](https://downforeveryoneorjustme.com/relay.s3auth.com).

**Comment by CherryDT** [comment]
Still not working :(

**Comment by yegor256** [comment]
@CherryDT it's up and running. It took some time to upgrade it from Java8 to Java17, but now it's all good.

**Comment by CherryDT** [comment]
Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/s3auth#405` is not assigned, can't get performer
