### ISSUE TITLE
MainTest.java:51-52: Test doesn't work since AWS...

### ISSUE THREAD

**Issue by davvd** [yegor256/s3auth#95]
Puzzle `33-9ff485f7` in `s3auth-relay/src/test/java/com/s3auth/relay/MainTest.java:51-52` has to be resolved: Test doesn't work since AWS Dynamo config is not available in runtime. We should find a way to mock it properly.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by darkled** [comment]
@davvd @yegor256 `MainTest` has been modified, but there is still a problem which do not allow to get it fixed completely. It is in the method `com.s3auth.relay.LocalHost.isIt(String)` which has to be extended 
* either with (that will break other tests)
```java
public static boolean isIt(@NotNull final String name) {
    return "relay.s3auth.com".equals(name)
        || StringUtils.startsWith(name, "localhost");
}
```

* or with mocking this method 
    * which is not allowed with standard mockito since `LocalHost` is a final class
    * and it is not working with powermock as well because of the [defect in powermock](https://code.google.com/p/powermock/issues/detail?id=531) due to change in junit 4.12

**Comment by davvd** [comment]
@darkled you're working with this issue for 13 days already... do not forget to remove the TODO puzzle from the source code... -30 added to your rating, current score is: [+15](http://www.netbout.com/b/35091?open=rating)

**Comment by davvd** [comment]
@darkled this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 added to your rating, at the moment it is: [-15](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@davvd ok, no problem. I don't understand this rating concept, could explain it, please?

**Comment by yegor256** [comment]
@davvd assign @darkled back to this issue please

**Comment by yegor256** [comment]
@darkled create an account at www.netbout.com and give me your account name. I'll give you access to full stats of your profile

**Comment by darkled** [comment]
@yegor256 done, my account there is the same - *darkled*.

**Comment by yegor256** [comment]
@darkled check netbout again, you should have access now

**Comment by darkled** [comment]
@yegor256 yes, I have, thanks. Now it's clear.

**Comment by davvd** [comment]
> @davvd assign @darkled back to this issue please

@yegor256 done. @darkled you're assigned to this task. please proceed...

**Comment by darkled** [comment]
@davvd @yegor256 please, take into account that this issue cannot be finished without #254, so we'll have to wait some time.

**Comment by yegor256** [comment]
@davvd we're waiting for #254 here

**Comment by davvd** [comment]
> @davvd we're waiting for #254 here

@yegor256 OK, let's wait for #254

**Comment by davvd** [comment]
Done, the task is closed

**Comment by davvd** [comment]
my bad, it's not done, reopen

**Comment by darkled** [comment]
@davvd we're waiting for #257 as well

**Comment by davvd** [comment]
> @davvd we're waiting for #257 as well

@darkled yes, waiting for #257

**Comment by davvd** [comment]
@davvd since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@yegor256 FYI, the issue we were waiting for (#254) is fixed

**Comment by darkled** [comment]
@davvd assign someone else please

**Comment by davvd** [comment]
> @davvd assign someone else please

@darkled -30 points to your rating :(

**Comment by davvd** [comment]
> @davvd assign someone else please

@darkled someone else will help in this task, no problem at all

**Comment by davvd** [comment]
@yegor256 The task is done, thanks all, I am closing it
